### ISSUE TITLE
Unable to install with latest version of pip

### ISSUE THREAD

**Issue by sahithi-rp** [alsur/compare-requirements#2]
pip install compare-requirements
Collecting compare-requirements
  Using cached https://files.pythonhosted.org/packages/c1/48/f7bd2724230f459befc79924ae5ffa7cc5fe431c6602616259e396021b4d/compare-requirements-0.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/m9/jm57fpxx7j9g_7v8pv75jxm00000gn/T/pip-install-59o_bi9k/compare-requirements/setup.py", line 6, in <module>
        from pip.req import parse_requirements
    ModuleNotFoundError: No module named 'pip.req'

**Comment by Nekmo** [comment]
Fixed on PR-3.
