### ISSUE TITLE
error installing using pip

### ISSUE THREAD

**Issue by jainraje** [alsur/compare-requirements#4]
I'm re-opeining. the following error does not appear to be fixed.

pip install compare-requirements
Collecting compare-requirements
  Using cached https://files.pythonhosted.org/packages/c1/48/f7bd2724230f459befc79924ae5ffa7cc5fe431c6602616259e396021b4d/compare-requirements-0.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-x40npw_2/compare-requirements/setup.py", line 6, in <module>
        from pip.req import parse_requirements
    ModuleNotFoundError: No module named 'pip.req'

please advise how fix and/or install this package.

thank-you,
--R

**Comment by bityob** [comment]
@jainraje 

Download the package from git directly, and run `pip install .` to install the package.

```bash
root@39e2eafadd7f:/opt/compare-requirements# pip install .
Processing /opt/airs/compare-requirements
Building wheels for collected packages: compare-requirements
  Running setup.py bdist_wheel for compare-requirements ... done
  Stored in directory: /root/.cache/pip/wheels/28/44/08/44f2a5b3134685796d184c2caec8d2459d22b4219c33c67bce
Successfully built compare-requirements
Installing collected packages: compare-requirements
Successfully installed compare-requirements-0.2.1
```


The problem was with the `setup.py` file in line 6, which has been updated already -

```python
if LooseVersion(pip.__version__) >= "10.0.0":
    from pip._internal.req import parse_requirements
else:
    from pip.req import parse_requirements
```
